 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PhoneStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionPlan = { 'pro' : null } |
  { 'premium' : null } |
  { 'basic' : null };
export interface TrackedNumber {
  'id' : bigint,
  'status' : PhoneStatus,
  'nickname' : string,
  'user' : Principal,
  'phoneNumber' : string,
  'dateAdded' : bigint,
}
export interface TrackingEvent {
  'id' : bigint,
  'user' : Principal,
  'timestamp' : bigint,
  'phoneNumber' : string,
  'location' : string,
  'eventType' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'plan' : SubscriptionPlan }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrackedNumber' : ActorMethod<[string, string], bigint>,
  'addTrackingEvent' : ActorMethod<[bigint, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFullHistory' : ActorMethod<[], Array<TrackingEvent>>,
  'getNumberHistory' : ActorMethod<[bigint], Array<TrackingEvent>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionPlan' : ActorMethod<[], SubscriptionPlan>,
  'getTrackedNumbers' : ActorMethod<[], Array<TrackedNumber>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeTrackedNumber' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setSubscriptionPlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateNumberStatus' : ActorMethod<[bigint, PhoneStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];